version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: '52.55.240.209 -> http://tv-backend:80'
      STAGE: 'production'
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - tv-backend
    networks:
      - tv-backend-net

  tv-backend:
    build: .
    ports:
      - "8001:80"  # Expose the backend's internal port for routing through https-portal
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
    networks:
      - tv-backend-net
    image:
      backend:latest

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres # no idea what this envvar is doing
    ports:
      - "1234:5432"
    networks:
      - tv-backend-net
    restart: unless-stopped
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  https-portal-data:

networks:
  tv-backend-net:
