services:
  tv-backend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - "postgres"
    networks:
      - "tv-backend-net"
    image:
      backend:latest

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /data/postgres # no idea what this envvar is doing
    ports:
      - "1234:5432"
    networks:
      - "tv-backend-net"
    restart: unless-stopped
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  tv-backend-net:
